apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
nameSuffix: -dev
images:
  - name: ghcr.io/OWNER/vinuthna.io
    newTag: latest
replicas: [{ name: portfolio, count: 1 }]
patches:
  - target: { kind: Ingress, name: portfolio }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.portfolio.example.com
