apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: portfolio
  namespace: portfolio
  labels: { release: monitoring }
spec:
  jobName: portfolio
  interval: 30s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static: [http://portfolio.portfolio.svc.cluster.local/healthz]
